import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "../Components/HeaderComponent";
import Image from "next/image";
import phone1 from "@/public/phone1.png";
import Link from "next/link";
import logo from "@/public/logo.png";
import whatsapp1 from "@/public/whatsapp1.png";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderComponent />
      {children}
      </body>
    </html>
  );
}
